/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectofinalui;

/**
 *
 * @author sduran
 */
public class MostrarTeatro extends javax.swing.JFrame {

    /**
     * Creates new form MostrarTeatro
     */
    public MostrarTeatro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        BtnSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectofinalui/telon.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 48, 200, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectofinalui/butaca-vip.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(228, 284, 86, 101));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectofinalui/butaca-vip.jpg"))); // NOI18N
        jLabel3.setText("jLabel2");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(228, 132, 86, 101));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectofinalui/butaca-vip.jpg"))); // NOI18N
        jLabel4.setText("jLabel2");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(228, 0, 86, 101));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectofinalui/butaca-vip.jpg"))); // NOI18N
        jLabel5.setText("jLabel2");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(324, 219, 86, 101));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectofinalui/butaca-vip.jpg"))); // NOI18N
        jLabel6.setText("jLabel2");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(324, 66, 86, 101));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectofinalui/GradPref.jpg"))); // NOI18N
        jLabel10.setText("jLabel7");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(413, 0, 61, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectofinalui/GradPref.jpg"))); // NOI18N
        jLabel11.setText("jLabel7");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 144, 61, -1));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectofinalui/GradPref.jpg"))); // NOI18N
        jLabel12.setText("jLabel7");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 239, 61, -1));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectofinalui/GradPref.jpg"))); // NOI18N
        jLabel13.setText("jLabel7");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 66, 61, -1));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectofinalui/GradPref.jpg"))); // NOI18N
        jLabel14.setText("jLabel7");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 304, 61, -1));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectofinalui/GradPref.jpg"))); // NOI18N
        jLabel15.setText("jLabel7");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(491, 0, 61, -1));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectofinalui/GradPref.jpg"))); // NOI18N
        jLabel16.setText("jLabel7");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(491, 144, 61, -1));

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectofinalui/GradPref.jpg"))); // NOI18N
        jLabel17.setText("jLabel7");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(498, 239, 61, -1));

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectofinalui/GradPref.jpg"))); // NOI18N
        jLabel18.setText("jLabel7");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(491, 71, 61, -1));

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectofinalui/GradPref.jpg"))); // NOI18N
        jLabel19.setText("jLabel7");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(498, 304, 61, -1));

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectofinalui/GradPref.jpg"))); // NOI18N
        jLabel20.setText("jLabel7");
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(636, 71, 61, -1));

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectofinalui/GradPref.jpg"))); // NOI18N
        jLabel21.setText("jLabel7");
        getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(636, 239, 61, -1));

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectofinalui/GradPref.jpg"))); // NOI18N
        jLabel22.setText("jLabel7");
        getContentPane().add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(633, 0, 61, -1));

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectofinalui/GradPref.jpg"))); // NOI18N
        jLabel23.setText("jLabel7");
        getContentPane().add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 304, 61, -1));

        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectofinalui/GradPref.jpg"))); // NOI18N
        jLabel24.setText("jLabel7");
        getContentPane().add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(562, 0, 61, -1));

        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectofinalui/GradPref.jpg"))); // NOI18N
        jLabel25.setText("jLabel7");
        getContentPane().add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(562, 71, 61, -1));

        jLabel26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectofinalui/GradPref.jpg"))); // NOI18N
        jLabel26.setText("jLabel7");
        getContentPane().add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(565, 239, 61, -1));

        jLabel27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectofinalui/GradPref.jpg"))); // NOI18N
        jLabel27.setText("jLabel7");
        getContentPane().add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(562, 144, 61, -1));

        jLabel28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectofinalui/GradPref.jpg"))); // NOI18N
        jLabel28.setText("jLabel7");
        getContentPane().add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(569, 304, 61, -1));

        jLabel29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectofinalui/GradPref.jpg"))); // NOI18N
        jLabel29.setText("jLabel7");
        getContentPane().add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(633, 144, 61, -1));

        jLabel30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectofinalui/GradPref.jpg"))); // NOI18N
        jLabel30.setText("jLabel7");
        getContentPane().add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(712, 144, 61, -1));

        jLabel31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectofinalui/GradPref.jpg"))); // NOI18N
        jLabel31.setText("jLabel7");
        getContentPane().add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(707, 71, 61, -1));

        jLabel32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectofinalui/GradPref.jpg"))); // NOI18N
        jLabel32.setText("jLabel7");
        getContentPane().add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(707, 239, 61, -1));

        jLabel33.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectofinalui/GradPref.jpg"))); // NOI18N
        jLabel33.setText("jLabel7");
        getContentPane().add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(707, 0, 61, -1));

        jLabel34.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectofinalui/GradPref.jpg"))); // NOI18N
        jLabel34.setText("jLabel7");
        getContentPane().add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(711, 304, 61, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectofinalui/graderia.png"))); // NOI18N
        jLabel8.setText("jLabel8");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(837, 26, 267, 314));

        BtnSalir.setFont(new java.awt.Font("SimSun", 1, 14)); // NOI18N
        BtnSalir.setText("Salir");
        BtnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSalirActionPerformed(evt);
            }
        });
        getContentPane().add(BtnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 320, 137, 75));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSalirActionPerformed
        dispose();
    }//GEN-LAST:event_BtnSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MostrarTeatro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MostrarTeatro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MostrarTeatro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MostrarTeatro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MostrarTeatro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    // End of variables declaration//GEN-END:variables
}
