/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectofinalui;

/**
 *
 * @author sduran
 */
public class UserInterface extends javax.swing.JFrame {

    /**
     * Creates new form UserInterface
     */
    public UserInterface() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButton1 = new javax.swing.JRadioButton();
        BtnRealizarReserva = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        BtnMostrarEspera = new javax.swing.JButton();
        BtnTeatro = new javax.swing.JButton();
        BtnMostrarReservas2 = new javax.swing.JButton();
        BtnGananciasTotales = new javax.swing.JButton();
        BtnGananciasLocalidad1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        jRadioButton1.setText("jRadioButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 153, 153));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BtnRealizarReserva.setBackground(new java.awt.Color(255, 255, 255));
        BtnRealizarReserva.setFont(new java.awt.Font("SimSun", 1, 14)); // NOI18N
        BtnRealizarReserva.setText("Realizar Reserva");
        BtnRealizarReserva.setToolTipText("");
        BtnRealizarReserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRealizarReservaActionPerformed(evt);
            }
        });
        getContentPane().add(BtnRealizarReserva, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 110, 261, 65));

        jTextField1.setFont(new java.awt.Font("SimSun", 1, 18)); // NOI18N
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.setText("Boleteria del Teatro ");
        jTextField1.setBorder(new javax.swing.border.MatteBorder(null));
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 40, 285, 70));

        BtnMostrarEspera.setBackground(new java.awt.Color(255, 255, 255));
        BtnMostrarEspera.setFont(new java.awt.Font("SimSun", 1, 14)); // NOI18N
        BtnMostrarEspera.setText("Mostrar Listas de Espera");
        BtnMostrarEspera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnMostrarEsperaActionPerformed(evt);
            }
        });
        getContentPane().add(BtnMostrarEspera, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 250, 261, 62));

        BtnTeatro.setBackground(new java.awt.Color(255, 255, 255));
        BtnTeatro.setFont(new java.awt.Font("SimSun", 1, 14)); // NOI18N
        BtnTeatro.setText("Mostrar Teatro");
        BtnTeatro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnTeatroActionPerformed(evt);
            }
        });
        getContentPane().add(BtnTeatro, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 250, 281, 62));

        BtnMostrarReservas2.setBackground(new java.awt.Color(255, 255, 255));
        BtnMostrarReservas2.setFont(new java.awt.Font("SimSun", 1, 14)); // NOI18N
        BtnMostrarReservas2.setText("Mostrar Reservas ");
        BtnMostrarReservas2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnMostrarReservas2ActionPerformed(evt);
            }
        });
        getContentPane().add(BtnMostrarReservas2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 180, 261, 62));

        BtnGananciasTotales.setBackground(new java.awt.Color(255, 255, 255));
        BtnGananciasTotales.setFont(new java.awt.Font("SimSun", 1, 14)); // NOI18N
        BtnGananciasTotales.setText("Mostrar Ganancias Totales");
        BtnGananciasTotales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnGananciasTotalesActionPerformed(evt);
            }
        });
        getContentPane().add(BtnGananciasTotales, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 110, 281, 65));

        BtnGananciasLocalidad1.setBackground(new java.awt.Color(255, 255, 255));
        BtnGananciasLocalidad1.setFont(new java.awt.Font("SimSun", 1, 14)); // NOI18N
        BtnGananciasLocalidad1.setText("Mostrar Ganancias por Localidad");
        BtnGananciasLocalidad1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnGananciasLocalidad1ActionPerformed(evt);
            }
        });
        getContentPane().add(BtnGananciasLocalidad1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 180, -1, 62));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectofinalui/Teatro.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, -44, 960, 420));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void BtnRealizarReservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRealizarReservaActionPerformed
        RealizarReserva fra=new RealizarReserva();
        fra.setVisible(true);
    }//GEN-LAST:event_BtnRealizarReservaActionPerformed

    private void BtnGananciasLocalidad1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnGananciasLocalidad1ActionPerformed
        GananciasXLocalidad fra=new GananciasXLocalidad();
        fra.setVisible(true);
    }//GEN-LAST:event_BtnGananciasLocalidad1ActionPerformed

    private void BtnMostrarReservas2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnMostrarReservas2ActionPerformed
        MostrarReservas fra=new MostrarReservas();
        fra.setVisible(true);
    }//GEN-LAST:event_BtnMostrarReservas2ActionPerformed

    private void BtnMostrarEsperaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnMostrarEsperaActionPerformed
        ListaEspera fra=new ListaEspera();
        fra.setVisible(true);
    }//GEN-LAST:event_BtnMostrarEsperaActionPerformed

    private void BtnTeatroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnTeatroActionPerformed
        MostrarTeatro fra=new MostrarTeatro();
        fra.setVisible(true);
    }//GEN-LAST:event_BtnTeatroActionPerformed

    private void BtnGananciasTotalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnGananciasTotalesActionPerformed
        GananciasTotales fra=new GananciasTotales();
        fra.setVisible(true);
    }//GEN-LAST:event_BtnGananciasTotalesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserInterface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnGananciasLocalidad1;
    private javax.swing.JButton BtnGananciasTotales;
    private javax.swing.JButton BtnMostrarEspera;
    private javax.swing.JButton BtnMostrarReservas2;
    private javax.swing.JButton BtnRealizarReserva;
    private javax.swing.JButton BtnTeatro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
